# Generated by Django 6.0.4 on 2026-04-09

from django.db import migrations, models


def normalize_social_platform(apps, schema_editor):
    SocialMedia = apps.get_model("app", "SocialMedia")
    mapping = {
        "github": "github",
        "linkedin": "linkedin",
        "instagram": "instagram",
        "twitter": "twitter",
        "x": "twitter",
        "facebook": "facebook",
        "youtube": "youtube",
        "email": "email",
        "mail": "email",
        "website": "website",
        "web": "website",
    }

    for item in SocialMedia.objects.all():
        current_value = (item.platform or "").strip().lower()
        item.platform = mapping.get(current_value, "website")
        item.save(update_fields=["platform"])


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_project_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="socialmedia",
            old_name="name",
            new_name="platform",
        ),
        migrations.RunPython(normalize_social_platform, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="socialmedia",
            name="platform",
            field=models.CharField(
                choices=[
                    ("github", "GitHub"),
                    ("linkedin", "LinkedIn"),
                    ("instagram", "Instagram"),
                    ("twitter", "X (Twitter)"),
                    ("facebook", "Facebook"),
                    ("youtube", "YouTube"),
                    ("email", "Email"),
                    ("website", "Website"),
                ],
                default="github",
                max_length=30,
            ),
        ),
    ]
